Add resuable workflows for deployment

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -1,356 +1,182 @@
 name: Solar System Workflow
 
-on: 
+on:
   workflow_dispatch:
   push:
     branches:
       - main
-      - 'feature/*'
+      - "feature/*"
 
 env:
   MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
   MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
   MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
-    
+
 jobs:
-    unit-testing:
-        # strategy:
-        #   matrix:
-        #     node-version: [18, 20]
-        #     os: [ubuntu-latest, windows-latest]
-        #     exclude:
-        #       - node-version: 20
-        #         os: windows-latest
-        strategy:
-          matrix:
-            node-version: [20]
-            os: [ubuntu-latest]
+  unit-testing:
+    # strategy:
+    #   matrix:
+    #     node-version: [18, 20]
+    #     os: [ubuntu-latest, windows-latest]
+    #     exclude:
+    #       - node-version: 20
+    #         os: windows-latest
+    strategy:
+      matrix:
+        node-version: [20]
+        os: [ubuntu-latest]
 
-        # Servive can be used to run a MongoDB instance for testing purposes. 
-        # A service is a separate container that runs alongside the job's main container, 
-        # allowing you to run dependencies like databases or other services needed for your tests.
-        # Here, you can specify the image of your test database (e.g., MongoDB) and the ports to expose.
+    # Servive can be used to run a MongoDB instance for testing purposes.
+    # A service is a separate container that runs alongside the job's main container,
+    # allowing you to run dependencies like databases or other services needed for your tests.
+    # Here, you can specify the image of your test database (e.g., MongoDB) and the ports to expose.
 
-        services:
-          mongo:
-            image: mongo:non-prod
-            ports:
-              - 27017:27017
+    services:
+      mongo:
+        image: mongo:non-prod
+        ports:
+          - 27017:27017
 
-        # These environment variables will be available to all steps in the job.
-        # They will take precedence over the global environment variables defined at the workflow/repo level, 
-        # allowing you to override them for this specific job if needed.
+    # These environment variables will be available to all steps in the job.
+    # They will take precedence over the global environment variables defined at the workflow/repo level,
+    # allowing you to override them for this specific job if needed.
 
-        env:
-          # The mongo_uri is a local connection string that points to the MongoDB service running in the 
-          # container.
-          MONGO_URI: "mongodb://localhost:27017/superData"
-          MONGO_USERNAME: non-prod-username
-          MONGO_PASSWORD: non-prod-password
+    env:
+      # The mongo_uri is a local connection string that points to the MongoDB service running in the
+      # container.
+      MONGO_URI: "mongodb://localhost:27017/superData"
+      MONGO_USERNAME: non-prod-username
+      MONGO_PASSWORD: non-prod-password
 
-        name: Unit Testing
-        runs-on: ${{ matrix.os }}
-        steps:
-        - name: Checkout Repository
-          uses: actions/checkout@v4
-
-        - name: Setup NodeJS Version
-          uses: actions/setup-node@v3
-          with:
-            node-version: ${{ matrix.node-version }}
-
-        - name: Cache Node Modules
-          uses: actions/cache@v3
-          with:
-            path: node_modules
-            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-    
-        - name: Install Dependencies
-          run: npm install
- 
-        - name: Unit Testing
-          id: node-test
-          run: npm test
-          
-        - name: Archive Test Result
-          if: always()
-          uses: actions/upload-artifact@v4
-          with:
-            name: Mocha-Test-Result
-            path: test-results.xml
-
-    code-coverage:
-        name: Code Coverage
-        runs-on: ubuntu-latest
-
-        # Job container allows you to specify a Docker image that will be used as the 
-        # execution environment for all steps in the job.
-        # We don't need to set up Node.js manually in this job since the container image (node:18) 
-        # already includes Node.js.
-       
-        container:
-          image: node:18
-
-        services:
-          mongo:
-            image: mongo:non-prod
-            options:
-              --name mongo
-
-            # We don't need to expose the port to the host machine since the tests will run inside the container,
-            # and they can access the MongoDB service using the internal network.
-
-        env:
-          # The mongo_uri now can use the service name (mongo) as the hostname,
-          # which allows the tests to connect to the MongoDB service running in the container.
-          MONGO_URI: "mongodb://mongo:27017/superData"
-          MONGO_USERNAME: non-prod-username
-          MONGO_PASSWORD: non-prod-password
-
-        steps:
-        - name: Checkout Repository
-          uses: actions/checkout@v4
-
-        # - name: Setup NodeJS Version
-        #   uses: actions/setup-node@v3
-        #   with:
-        #     node-version: 18
-    
-        - name: Install Dependencies
-          run: npm install
-
-        - name: Run Code Coverage
-          run: npm run coverage
-
-        - name: Upload Code Coverage Report
-          uses: actions/upload-artifact@v4
-          with:
-            name: Code-Coverage-Report
-            path: coverage/lcov-report
-            retention-days: 5
-
-    docker:
-        name: Containerization
-        runs-on: ubuntu-latest
-        needs: [unit-testing, code-coverage]
-        steps:
-        - name: Checkout Repository
-          uses: actions/checkout@v4
-
-        - name: Docker login
-          uses: docker/login-action@v2
-          with:
-            username: ${{ vars.DOCKER_USERNAME }}
-            password: ${{ secrets.DOCKER_PASSWORD }}
-
-        - name: Build Docker Image
-          uses: docker/build-push-action@v3
-          with:
-            context: . # Search for Dockerfile in the root directory
-            push: false
-            tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
-
-        - name: Test Docker Image
-          run: |
-            docker run --rm ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }} npm test
-
-        - name: Push Docker Image
-          uses: docker/build-push-action@v3
-          with:
-            context: . # Search for Dockerfile in the root directory
-            push: true
-            tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
-
-    dev-deploy:
-      name: Deploy on Kubernetes
-      # The if condition is used to specify that this job should only run when the workflow is triggered by
-      # a push to a branch that contains 'feature/' in its name.
-      if: contains(github.ref, 'feature/')
-
-      # The environment keyword in GitHub Actions is used to specify the environment to which the job will be deployed.
-      # This is applied below the job level, and it allows you to define environment-specific settings, such as URLs or secrets, 
-      # that can be used in the steps of the job.
-      # Difference between env and environment: 
-      # env is used to set environment variables that are available to the steps in the job, 
-      # while environment is used to specify the deployment environment and its associated settings.
-      environment:
-        name: development
-        url: http://${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
-
-      runs-on: ubuntu-latest     
-      outputs:
-        APP_INGRESS_HOST: ${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
-      needs: docker
-      if: failure()
-      steps:
+    name: Unit Testing
+    runs-on: ${{ matrix.os }}
+    steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Set up Kubeconfig
-        uses: azure/k8s-set-context@v3
+      - name: Setup NodeJS Version
+        uses: actions/setup-node@v3
         with:
-          kubeconfig: ${{ secrets.KUBE_CONFIG }}
-      
-      - name: Install Kubectly CLI
-        uses: azure/setup-kubectl@v3
+          node-version: ${{ matrix.node-version }}
+
+      - name: Cache Node Modules
+        uses: actions/cache@v3
         with:
-          version: 'latest'
-        
-      - name: Fetch Kubernetes cluster information
-        run: |
-          kubectl cluster-info
-          echo "------------------------------------"
-          kubectl get nodes
+          path: node_modules
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
 
-      # Ingress is a Kubernetes resource that manages external access to services within a cluster, typically HTTP.
-      - name: Get Ingress IP
-        id: get-ingress-ip
-        # Here we are saving the Ingress IP to a GitHub Actions environment variable (INGRESS_IP) using the $GITHUB_ENV file,
-        # which allows us to use this variable in subsequent steps of the workflow.
-        run: |
-          INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
-          echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV
-      
-      - name: Replace tokens in Manifest file
-        uses: cschleiden/replace-tokens@v1
+      - name: Install Dependencies
+        run: npm install
+
+      - name: Unit Testing
+        id: node-test
+        run: npm test
+
+      - name: Archive Test Result
+        if: always()
+        uses: actions/upload-artifact@v4
         with:
-          tokenPrefix: '_{_'
-          tokenSuffix: '_}_'
-          files: kubernetes/development/*.yaml
-        env:
-          NAMESPACE: 'dev'
-          REPLICAS: '2'
-          IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
-          INGRESS_IP: ${{ env.INGRESS_IP }} 
+          name: Mocha-Test-Result
+          path: test-results.xml
 
-      - name: Check files
-        run: |
-          echo "Modified Deployment Manifest:"
-          cat kubernetes/development/deployment.yaml
+  code-coverage:
+    name: Code Coverage
+    runs-on: ubuntu-latest
 
-      - name: Create MongoDB Secret
-        run: |
-          kubectl create secret generic mongo-db-creds \
-            --from-literal=mongo_uri=${{ env.MONGO_URI }} \
-            --from-literal=username=${{ vars.MONGO_USERNAME }} \
-            --from-literal=password=${{ secrets.MONGO_PASSWORD }} \
-            -n dev --dry-run=client -o yaml | kubectl apply -f -
+    # Job container allows you to specify a Docker image that will be used as the
+    # execution environment for all steps in the job.
+    # We don't need to set up Node.js manually in this job since the container image (node:18)
+    # already includes Node.js.
 
-      - name: Deploy to Kubernetes
-        run: |
-          kubectl apply -f kubernetes/development/
+    container:
+      image: node:18
 
-      - name: Set App Ingress Host URL
-        id: set-ingress-url
-        run: |
-            echo "APP_INGRESS_HOST=$(kubectl get ingress -n dev solar-system-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT
-    
-    dev-integration-test:
-      name: Integration Testing
-      runs-on: ubuntu-latest
-      needs: dev-deploy
-      if: contains(github.ref, 'feature/')
-      steps:
-      - name: Test URL output using curl and JQ
-        env:
-          APP_INGRESS_HOST: ${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
-        run: |
-          echo $APP_INGRESS_HOST
-          RESPONSE=$(curl -s http://$APP_INGRESS_HOST/live)
-          echo "Response from the application: $RESPONSE"
-          # Here we are using JQ to parse the JSON response and extract the value of the "status" field.
-          STATUS=$(echo $RESPONSE | jq -r '.status')
-          echo "Extracted status: $STATUS"
-          if [ "$STATUS" != "ok" ]; then
-            echo "Integration test failed: Expected status 'ok' but got '$STATUS'"
-            exit 1
-          else
-            echo "Integration test passed: Status is 'ok'"
-          fi
-    
-    prod-deploy:
-      if: github.ref == 'refs/heads/main'
-      needs: docker
-      name: Deploy on Kubernetes
-      environment:
-        # We have configured several production environment rules in the repository settings, 
-        # If even one rule fails, the deployment will not proceed, and the job will be marked as failed.
-        name: production
-        url: http://${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
+    services:
+      mongo:
+        image: mongo:non-prod
+        options: --name mongo
 
-      runs-on: ubuntu-latest     
-      outputs:
-        APP_INGRESS_HOST: ${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
-      needs: docker
-      if: failure()
-      steps:
+        # We don't need to expose the port to the host machine since the tests will run inside the container,
+        # and they can access the MongoDB service using the internal network.
+
+    env:
+      # The mongo_uri now can use the service name (mongo) as the hostname,
+      # which allows the tests to connect to the MongoDB service running in the container.
+      MONGO_URI: "mongodb://mongo:27017/superData"
+      MONGO_USERNAME: non-prod-username
+      MONGO_PASSWORD: non-prod-password
+
+    steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Set up Kubeconfig
-        uses: azure/k8s-set-context@v3
+      # - name: Setup NodeJS Version
+      #   uses: actions/setup-node@v3
+      #   with:
+      #     node-version: 18
+
+      - name: Install Dependencies
+        run: npm install
+
+      - name: Run Code Coverage
+        run: npm run coverage
+
+      - name: Upload Code Coverage Report
+        uses: actions/upload-artifact@v4
         with:
-          kubeconfig: ${{ secrets.KUBE_CONFIG }}
-      
-      - name: Install Kubectly CLI
-        uses: azure/setup-kubectl@v3
+          name: Code-Coverage-Report
+          path: coverage/lcov-report
+          retention-days: 5
+
+  docker:
+    name: Containerization
+    runs-on: ubuntu-latest
+    needs: [unit-testing, code-coverage]
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Docker login
+        uses: docker/login-action@v2
         with:
-          version: 'latest'
-        
-      - name: Fetch Kubernetes cluster information
-        run: |
-          kubectl cluster-info
-          echo "------------------------------------"
-          kubectl get nodes
+          username: ${{ vars.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Get Ingress IP
-        id: get-ingress-ip
-        run: |
-          INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
-          echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV
-      
-      - name: Replace tokens in Manifest file
-        uses: cschleiden/replace-tokens@v1
+      - name: Build Docker Image
+        uses: docker/build-push-action@v3
         with:
-          tokenPrefix: '_{_'
-          tokenSuffix: '_}_'
-          files: kubernetes/production/*.yaml
-        env:
-          # Set these values in the secrets and variables section of the repository settings, 
-          # so that they can be securely accessed in the workflow.
-          NAMESPACE: 'prod'
-          REPLICAS: '3'
-          IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
-          INGRESS_IP: ${{ env.INGRESS_IP }} 
+          context: . # Search for Dockerfile in the root directory
+          push: false
+          tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
 
-      - name: Check files
+      - name: Test Docker Image
         run: |
-          echo "Modified Deployment Manifest:"
-          cat kubernetes/production/deployment.yaml
+          docker run --rm ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }} npm test
 
-      - name: Create MongoDB Secret
-        run: |
-          kubectl create secret generic mongo-db-creds \
-            --from-literal=mongo_uri=${{ env.MONGO_URI }} \
-            --from-literal=username=${{ vars.MONGO_USERNAME }} \
-            --from-literal=password=${{ secrets.MONGO_PASSWORD }} \
-            -n dev --dry-run=client -o yaml | kubectl apply -f -
+      - name: Push Docker Image
+        uses: docker/build-push-action@v3
+        with:
+          context: . # Search for Dockerfile in the root directory
+          push: true
+          tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
 
-      - name: Deploy to Kubernetes
-        run: |
-          kubectl apply -f kubernetes/development/
+  # Here we use a resuable workflow (reuse-deployment.yml) 
+  # to deploy the application to both development and production environments.
+  # We have to pass secrets from the main workfow to the reusable one
+  dev-deploy:
+    if: contains(github.ref, 'feature/')
+    needs: docker
+    uses: ./.github/workflows/reuse-deployment.yml
+    secrets:
+        k8-kubeconfig: ${{ secrets.KUBE_CONFIG }}
+        mongo-password: ${{ secrets.MONGO_PASSWORD }}
 
-      - name: Set App Ingress Host URL
-        id: set-ingress-url
-        run: |
-            echo "APP_INGRESS_HOST=$(kubectl get ingress -n dev solar-system-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT
-    
-    prod-integration-test:
-      if: github.ref == 'refs/heads/main'
-      name: Integration Testing
-      runs-on: ubuntu-latest
-      needs: prod-deploy
-      steps:
+  dev-integration-test:
+    name: Integration Testing
+    runs-on: ubuntu-latest
+    needs: dev-deploy
+    if: contains(github.ref, 'feature/')
+    steps:
       - name: Test URL output using curl and JQ
         env:
           APP_INGRESS_HOST: ${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
@@ -368,3 +194,39 @@ jobs:
             echo "Integration test passed: Status is 'ok'"
           fi
 
+  prod-deploy:
+    if: github.ref == 'refs/heads/main'
+    needs: docker
+    uses: ./.github/workflows/reuse-deployment.yml
+    secrets:
+        k8-kubeconfig: ${{ secrets.KUBE_CONFIG }}
+        mongo-password: ${{ secrets.MONGO_PASSWORD }}
+
+  prod-integration-test:
+    if: github.ref == 'refs/heads/main'
+    name: Integration Testing
+    runs-on: ubuntu-latest
+    needs: prod-deploy
+    steps:
+      - name: Test URL output using curl and JQ
+        env:
+          APP_INGRESS_HOST: ${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
+        run: |
+          echo $APP_INGRESS_HOST
+          RESPONSE=$(curl -s http://$APP_INGRESS_HOST/live)
+          echo "Response from the application: $RESPONSE"
+          # Here we are using JQ to parse the JSON response and extract the value of the "status" field.
+          STATUS=$(echo $RESPONSE | jq -r '.status')
+          echo "Extracted status: $STATUS"
+          if [ "$STATUS" != "ok" ]; then
+            echo "Integration test failed: Expected status 'ok' but got '$STATUS'"
+            exit 1
+          else
+            echo "Integration test passed: Status is 'ok'"
+          fi
+
+# Checkout github-actions-solar-system repostory, feature branch, yaml file
+# After the workflow finishes successfully, you can merge the branch to the main branch by raising a PR
+# After merging the PR, the prod-deploy and prod-integration-test jobs will be triggered, and the
+# application will be deployed to the production environment.
+# After the deployment, manual approval from one of the reviewers is required to proceed with the production deployment.
