Add if expressions on development and production jobs

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -163,6 +163,9 @@ jobs:
 
     dev-deploy:
       name: Deploy on Kubernetes
+      # The if condition is used to specify that this job should only run when the workflow is triggered by
+      # a push to a branch that contains 'feature/' in its name.
+      if: contains(github.ref, 'feature/')
 
       # The environment keyword in GitHub Actions is used to specify the environment to which the job will be deployed.
       # This is applied below the job level, and it allows you to define environment-specific settings, such as URLs or secrets, 
@@ -242,11 +245,11 @@ jobs:
         run: |
             echo "APP_INGRESS_HOST=$(kubectl get ingress -n dev solar-system-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT
     
-    integration-test:
+    dev-integration-test:
       name: Integration Testing
       runs-on: ubuntu-latest
       needs: dev-deploy
-      if: failure()
+      if: contains(github.ref, 'feature/')
       steps:
       - name: Test URL output using curl and JQ
         env:
@@ -264,3 +267,104 @@ jobs:
           else
             echo "Integration test passed: Status is 'ok'"
           fi
+    
+    prod-deploy:
+      if: github.ref == 'refs/heads/main'
+      needs: docker
+      name: Deploy on Kubernetes
+      environment:
+        # We have configured several production environment rules in the repository settings, 
+        # If even one rule fails, the deployment will not proceed, and the job will be marked as failed.
+        name: production
+        url: http://${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
+
+      runs-on: ubuntu-latest     
+      outputs:
+        APP_INGRESS_HOST: ${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
+      needs: docker
+      if: failure()
+      steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Set up Kubeconfig
+        uses: azure/k8s-set-context@v3
+        with:
+          kubeconfig: ${{ secrets.KUBE_CONFIG }}
+      
+      - name: Install Kubectly CLI
+        uses: azure/setup-kubectl@v3
+        with:
+          version: 'latest'
+        
+      - name: Fetch Kubernetes cluster information
+        run: |
+          kubectl cluster-info
+          echo "------------------------------------"
+          kubectl get nodes
+
+      - name: Get Ingress IP
+        id: get-ingress-ip
+        run: |
+          INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+          echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV
+      
+      - name: Replace tokens in Manifest file
+        uses: cschleiden/replace-tokens@v1
+        with:
+          tokenPrefix: '_{_'
+          tokenSuffix: '_}_'
+          files: kubernetes/production/*.yaml
+        env:
+          # Set these values in the secrets and variables section of the repository settings, 
+          # so that they can be securely accessed in the workflow.
+          NAMESPACE: 'prod'
+          REPLICAS: '3'
+          IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
+          INGRESS_IP: ${{ env.INGRESS_IP }} 
+
+      - name: Check files
+        run: |
+          echo "Modified Deployment Manifest:"
+          cat kubernetes/production/deployment.yaml
+
+      - name: Create MongoDB Secret
+        run: |
+          kubectl create secret generic mongo-db-creds \
+            --from-literal=mongo_uri=${{ env.MONGO_URI }} \
+            --from-literal=username=${{ vars.MONGO_USERNAME }} \
+            --from-literal=password=${{ secrets.MONGO_PASSWORD }} \
+            -n dev --dry-run=client -o yaml | kubectl apply -f -
+
+      - name: Deploy to Kubernetes
+        run: |
+          kubectl apply -f kubernetes/development/
+
+      - name: Set App Ingress Host URL
+        id: set-ingress-url
+        run: |
+            echo "APP_INGRESS_HOST=$(kubectl get ingress -n dev solar-system-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT
+    
+    prod-integration-test:
+      if: github.ref == 'refs/heads/main'
+      name: Integration Testing
+      runs-on: ubuntu-latest
+      needs: prod-deploy
+      steps:
+      - name: Test URL output using curl and JQ
+        env:
+          APP_INGRESS_HOST: ${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
+        run: |
+          echo $APP_INGRESS_HOST
+          RESPONSE=$(curl -s http://$APP_INGRESS_HOST/live)
+          echo "Response from the application: $RESPONSE"
+          # Here we are using JQ to parse the JSON response and extract the value of the "status" field.
+          STATUS=$(echo $RESPONSE | jq -r '.status')
+          echo "Extracted status: $STATUS"
+          if [ "$STATUS" != "ok" ]; then
+            echo "Integration test failed: Expected status 'ok' but got '$STATUS'"
+            exit 1
+          else
+            echo "Integration test passed: Status is 'ok'"
+          fi
+
