Setup integration tests

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -164,16 +164,18 @@ jobs:
     dev-deploy:
       name: Deploy on Kubernetes
       runs-on: ubuntu-latest
+      outputs:
+        APP_INGRESS_HOST: ${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
       needs: docker
       if: failure()
       steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      # - name: Set up Kubeconfig
-      #   run: |
-      #     mkdir -p $HOME/.kube
-      #     echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
+      - name: Set up Kubeconfig
+        uses: azure/k8s-set-context@v3
+        with:
+          kubeconfig: ${{ secrets.KUBE_CONFIG }}
       
       - name: Install Kubectly CLI
         uses: azure/setup-kubectl@v3
@@ -185,3 +187,69 @@ jobs:
           kubectl cluster-info
           echo "------------------------------------"
           kubectl get nodes
+
+      # Ingress is a Kubernetes resource that manages external access to services within a cluster, typically HTTP.
+      - name: Get Ingress IP
+        id: get-ingress-ip
+        # Here we are saving the Ingress IP to a GitHub Actions environment variable (INGRESS_IP) using the $GITHUB_ENV file,
+        # which allows us to use this variable in subsequent steps of the workflow.
+        run: |
+          INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+          echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV
+      
+      - name: Replace tokens in Manifest file
+        uses: cschleiden/replace-tokens@v1
+        with:
+          tokenPrefix: '_{_'
+          tokenSuffix: '_}_'
+          files: kubernetes/development/*.yaml
+        env:
+          NAMESPACE: 'dev'
+          REPLICAS: '2'
+          IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
+          INGRESS_IP: ${{ env.INGRESS_IP }} 
+
+      - name: Check files
+        run: |
+          echo "Modified Deployment Manifest:"
+          cat kubernetes/development/deployment.yaml
+
+      - name: Create MongoDB Secret
+        run: |
+          kubectl create secret generic mongo-db-creds \
+            --from-literal=mongo_uri=${{ env.MONGO_URI }} \
+            --from-literal=username=${{ vars.MONGO_USERNAME }} \
+            --from-literal=password=${{ secrets.MONGO_PASSWORD }} \
+            -n dev --dry-run=client -o yaml | kubectl apply -f -
+
+      - name: Deploy to Kubernetes
+        run: |
+          kubectl apply -f kubernetes/development/
+
+      - name: Set App Ingress Host URL
+        id: set-ingress-url
+        run: |
+            echo "APP_INGRESS_HOST=$(kubectl get ingress -n dev solar-system-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT
+    
+    integration-test:
+      name: Integration Testing
+      runs-on: ubuntu-latest
+      needs: dev-deploy
+      if: failure()
+      steps:
+      - name: Test URL output using curl and JQ
+        env:
+          APP_INGRESS_HOST: ${{ steps.set-ingress-url.outputs.APP_INGRESS_HOST }}
+        run: |
+          echo $APP_INGRESS_HOST
+          RESPONSE=$(curl -s http://$APP_INGRESS_HOST/live)
+          echo "Response from the application: $RESPONSE"
+          # Here we are using JQ to parse the JSON response and extract the value of the "status" field.
+          STATUS=$(echo $RESPONSE | jq -r '.status')
+          echo "Extracted status: $STATUS"
+          if [ "$STATUS" != "ok" ]; then
+            echo "Integration test failed: Expected status 'ok' but got '$STATUS'"
+            exit 1
+          else
+            echo "Integration test passed: Status is 'ok'"
+          fi
